# Generated by Django 5.2.1 on 2025-06-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_token_user_id_token_user_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='city',
        ),
    ]
