# Generated by Django 5.2.1 on 2025-06-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_game_usergamestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
